In [1]:
from __future__ import absolute_import, division, print_function

import tensorflow as tf

tf.enable_eager_execution()


In [2]:
tf.executing_eagerly() 

True

In [3]:
a = tf.constant([
    [[3,4,5], [5,6,1],[3,9,7], [5,3,1]],
    [[3,9,7], [5,3,1],[3,4,5], [5,6,1]],
    [[4,5,2], [0,4,3],[9,2,6], [5,4,8]],
    [[9,2,6], [5,4,8],[4,5,2], [0,4,3]]
], dtype=tf.float32)
a

<tf.Tensor: id=1, shape=(4, 4, 3), dtype=float32, numpy=
array([[[3., 4., 5.],
        [5., 6., 1.],
        [3., 9., 7.],
        [5., 3., 1.]],

       [[3., 9., 7.],
        [5., 3., 1.],
        [3., 4., 5.],
        [5., 6., 1.]],

       [[4., 5., 2.],
        [0., 4., 3.],
        [9., 2., 6.],
        [5., 4., 8.]],

       [[9., 2., 6.],
        [5., 4., 8.],
        [4., 5., 2.],
        [0., 4., 3.]]], dtype=float32)>

In [5]:
1 - a

<tf.Tensor: id=6, shape=(4, 4, 3), dtype=float32, numpy=
array([[[-2., -3., -4.],
        [-4., -5.,  0.],
        [-2., -8., -6.],
        [-4., -2.,  0.]],

       [[-2., -8., -6.],
        [-4., -2.,  0.],
        [-2., -3., -4.],
        [-4., -5.,  0.]],

       [[-3., -4., -1.],
        [ 1., -3., -2.],
        [-8., -1., -5.],
        [-4., -3., -7.]],

       [[-8., -1., -5.],
        [-4., -3., -7.],
        [-3., -4., -1.],
        [ 1., -3., -2.]]], dtype=float32)>

In [11]:
tf.slice(a, [0,1,0],[-1,-1,-1])

<tf.Tensor: id=27, shape=(4, 1, 3), dtype=float32, numpy=
array([[[5., 6., 1.]],

       [[5., 3., 1.]],

       [[0., 4., 3.]],

       [[5., 4., 8.]]], dtype=float32)>

In [6]:
a[[]]

<tf.Tensor: id=1, shape=(4, 4, 3), dtype=float32, numpy=
array([[[3., 4., 5.],
        [5., 6., 1.],
        [3., 9., 7.],
        [5., 3., 1.]],

       [[3., 9., 7.],
        [5., 3., 1.],
        [3., 4., 5.],
        [5., 6., 1.]],

       [[4., 5., 2.],
        [0., 4., 3.],
        [9., 2., 6.],
        [5., 4., 8.]],

       [[9., 2., 6.],
        [5., 4., 8.],
        [4., 5., 2.],
        [0., 4., 3.]]], dtype=float32)>

In [ ]:
x